# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import serviceContract_pb2 as serviceContract__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in serviceContract_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToxicityScannerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeMessage = channel.unary_unary(
                '/toxicity.ToxicityScanner/AnalyzeMessage',
                request_serializer=serviceContract__pb2.EncryptedRequest.SerializeToString,
                response_deserializer=serviceContract__pb2.VerdictResponse.FromString,
                _registered_method=True)


class ToxicityScannerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToxicityScannerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeMessage,
                    request_deserializer=serviceContract__pb2.EncryptedRequest.FromString,
                    response_serializer=serviceContract__pb2.VerdictResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'toxicity.ToxicityScanner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('toxicity.ToxicityScanner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToxicityScanner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/toxicity.ToxicityScanner/AnalyzeMessage',
            serviceContract__pb2.EncryptedRequest.SerializeToString,
            serviceContract__pb2.VerdictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
