# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serviceContract.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serviceContract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15serviceContract.proto\x12\x08toxicity\"@\n\x10\x45ncryptedRequest\x12\x0f\n\x07\x65nc_key\x18\x01 \x01(\t\x12\n\n\x02iv\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"A\n\x0fVerdictResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x10\n\x08is_toxic\x18\x03 \x01(\x08\x32\\\n\x0fToxicityScanner\x12I\n\x0e\x41nalyzeMessage\x12\x1a.toxicity.EncryptedRequest\x1a\x19.toxicity.VerdictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serviceContract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTEDREQUEST']._serialized_start=35
  _globals['_ENCRYPTEDREQUEST']._serialized_end=99
  _globals['_VERDICTRESPONSE']._serialized_start=101
  _globals['_VERDICTRESPONSE']._serialized_end=166
  _globals['_TOXICITYSCANNER']._serialized_start=168
  _globals['_TOXICITYSCANNER']._serialized_end=260
# @@protoc_insertion_point(module_scope)
